/**
 * 教材种子数据 - 人教版 (PEP) 初中英语
 * 可以持续补充更多版本和年级
 */
export interface TextbookWord {
  chinese: string
  english: string
}

export interface TextbookUnit {
  grade: string
  semester: string
  unit: string
  unitName: string
  words: TextbookWord[]
}

export interface Textbook {
  version: string
  versionName: string
  grades: string[]
}

// 可用的教材版本
export const TEXTBOOKS: Textbook[] = [
  { version: 'pep', versionName: '人教版 (PEP)', grades: ['三年级', '四年级', '五年级', '六年级', '七年级', '八年级', '九年级'] },
]

// 人教版七年级上册词汇
const PEP_7A_UNITS: TextbookUnit[] = [
  {
    grade: '七年级', semester: '上册', unit: 'Starter',
    unitName: '预备单元',
    words: [
      { chinese: '好的', english: 'good' },
      { chinese: '早晨', english: 'morning' },
      { chinese: '下午', english: 'afternoon' },
      { chinese: '晚上', english: 'evening' },
      { chinese: '你好', english: 'hello' },
      { chinese: '谢谢', english: 'thank' },
      { chinese: '什么', english: 'what' },
      { chinese: '名字', english: 'name' },
      { chinese: '遇见', english: 'meet' },
      { chinese: '也', english: 'too' },
    ]
  },
  {
    grade: '七年级', semester: '上册', unit: 'Unit 1',
    unitName: 'My name\'s Gina.',
    words: [
      { chinese: '名字', english: 'name' },
      { chinese: '好的', english: 'nice' },
      { chinese: '遇见', english: 'meet' },
      { chinese: '也', english: 'too' },
      { chinese: '你的', english: 'your' },
      { chinese: '他的', english: 'his' },
      { chinese: '她的', english: 'her' },
      { chinese: '是的', english: 'yes' },
      { chinese: '她', english: 'she' },
      { chinese: '他', english: 'he' },
      { chinese: '不', english: 'no' },
      { chinese: '不；没有', english: 'not' },
      { chinese: '零', english: 'zero' },
      { chinese: '一', english: 'one' },
      { chinese: '二', english: 'two' },
      { chinese: '三', english: 'three' },
      { chinese: '四', english: 'four' },
      { chinese: '五', english: 'five' },
      { chinese: '六', english: 'six' },
      { chinese: '七', english: 'seven' },
      { chinese: '八', english: 'eight' },
      { chinese: '九', english: 'nine' },
      { chinese: '电话', english: 'telephone' },
      { chinese: '号码', english: 'number' },
      { chinese: '第一', english: 'first' },
      { chinese: '最后的', english: 'last' },
      { chinese: '朋友', english: 'friend' },
      { chinese: '中国', english: 'China' },
      { chinese: '中间的', english: 'middle' },
      { chinese: '学校', english: 'school' },
    ]
  },
  {
    grade: '七年级', semester: '上册', unit: 'Unit 2',
    unitName: 'This is my sister.',
    words: [
      { chinese: '姐妹', english: 'sister' },
      { chinese: '母亲', english: 'mother' },
      { chinese: '父亲', english: 'father' },
      { chinese: '父母', english: 'parent' },
      { chinese: '兄弟', english: 'brother' },
      { chinese: '祖母', english: 'grandmother' },
      { chinese: '祖父', english: 'grandfather' },
      { chinese: '家庭', english: 'family' },
      { chinese: '那些', english: 'those' },
      { chinese: '这些', english: 'these' },
      { chinese: '谁', english: 'who' },
      { chinese: '他们', english: 'they' },
      { chinese: '女儿', english: 'daughter' },
      { chinese: '儿子', english: 'son' },
      { chinese: '堂兄弟', english: 'cousin' },
      { chinese: '叔叔', english: 'uncle' },
      { chinese: '阿姨', english: 'aunt' },
      { chinese: '亲爱的', english: 'dear' },
      { chinese: '照片', english: 'photo' },
      { chinese: '这里', english: 'here' },
      { chinese: '女孩', english: 'girl' },
      { chinese: '男孩', english: 'boy' },
    ]
  },
  {
    grade: '七年级', semester: '上册', unit: 'Unit 3',
    unitName: 'Is this your pencil?',
    words: [
      { chinese: '铅笔', english: 'pencil' },
      { chinese: '书', english: 'book' },
      { chinese: '橡皮', english: 'eraser' },
      { chinese: '书包', english: 'schoolbag' },
      { chinese: '字典', english: 'dictionary' },
      { chinese: '尺子', english: 'ruler' },
      { chinese: '钢笔', english: 'pen' },
      { chinese: '老师', english: 'teacher' },
      { chinese: '关于', english: 'about' },
      { chinese: '帮助', english: 'help' },
      { chinese: '欢迎', english: 'welcome' },
      { chinese: '笔记本', english: 'notebook' },
      { chinese: '棒球', english: 'baseball' },
      { chinese: '手表', english: 'watch' },
      { chinese: '电脑', english: 'computer' },
      { chinese: '游戏', english: 'game' },
      { chinese: '卡片', english: 'card' },
      { chinese: '图书馆', english: 'library' },
      { chinese: '询问', english: 'ask' },
      { chinese: '找到', english: 'find' },
      { chinese: '一些', english: 'some' },
      { chinese: '教室', english: 'classroom' },
      { chinese: '电子邮件', english: 'email' },
      { chinese: '打电话', english: 'call' },
      { chinese: '丢失', english: 'lost' },
      { chinese: '必须', english: 'must' },
      { chinese: '一套', english: 'set' },
    ]
  },
  {
    grade: '七年级', semester: '上册', unit: 'Unit 4',
    unitName: 'Where\'s my schoolbag?',
    words: [
      { chinese: '在哪里', english: 'where' },
      { chinese: '桌子', english: 'table' },
      { chinese: '床', english: 'bed' },
      { chinese: '书柜', english: 'bookcase' },
      { chinese: '沙发', english: 'sofa' },
      { chinese: '椅子', english: 'chair' },
      { chinese: '在…上面', english: 'on' },
      { chinese: '在…下面', english: 'under' },
      { chinese: '来', english: 'come' },
      { chinese: '房间', english: 'room' },
      { chinese: '帽子', english: 'hat' },
      { chinese: '头', english: 'head' },
      { chinese: '收音机', english: 'radio' },
      { chinese: '时钟', english: 'clock' },
      { chinese: '磁带', english: 'tape' },
      { chinese: '播放机', english: 'player' },
      { chinese: '模型', english: 'model' },
      { chinese: '飞机', english: 'plane' },
      { chinese: '整洁的', english: 'tidy' },
      { chinese: '但是', english: 'but' },
      { chinese: '我们的', english: 'our' },
      { chinese: '到处', english: 'everywhere' },
      { chinese: '总是', english: 'always' },
    ]
  },
  {
    grade: '七年级', semester: '上册', unit: 'Unit 5',
    unitName: 'Do you have a soccer ball?',
    words: [
      { chinese: '有', english: 'have' },
      { chinese: '球', english: 'ball' },
      { chinese: '网球', english: 'tennis' },
      { chinese: '排球', english: 'volleyball' },
      { chinese: '篮球', english: 'basketball' },
      { chinese: '足球', english: 'soccer' },
      { chinese: '乒乓球', english: 'ping-pong' },
      { chinese: '让', english: 'let' },
      { chinese: '去', english: 'go' },
      { chinese: '我们', english: 'we' },
      { chinese: '迟到的', english: 'late' },
      { chinese: '得到', english: 'get' },
      { chinese: '伟大的', english: 'great' },
      { chinese: '玩耍', english: 'play' },
      { chinese: '听起来', english: 'sound' },
      { chinese: '有趣的', english: 'interesting' },
      { chinese: '无聊的', english: 'boring' },
      { chinese: '有趣的', english: 'fun' },
      { chinese: '困难的', english: 'difficult' },
      { chinese: '轻松的', english: 'relaxing' },
      { chinese: '观看', english: 'watch' },
      { chinese: '相同的', english: 'same' },
      { chinese: '爱', english: 'love' },
      { chinese: '体育运动', english: 'sport' },
      { chinese: '仅', english: 'only' },
      { chinese: '容易的', english: 'easy' },
      { chinese: '在…以后', english: 'after' },
      { chinese: '班级', english: 'class' },
      { chinese: '同学', english: 'classmate' },
    ]
  },
  {
    grade: '七年级', semester: '上册', unit: 'Unit 6',
    unitName: 'Do you like bananas?',
    words: [
      { chinese: '香蕉', english: 'banana' },
      { chinese: '汉堡包', english: 'hamburger' },
      { chinese: '西红柿', english: 'tomato' },
      { chinese: '冰激凌', english: 'ice-cream' },
      { chinese: '沙拉', english: 'salad' },
      { chinese: '草莓', english: 'strawberry' },
      { chinese: '梨', english: 'pear' },
      { chinese: '牛奶', english: 'milk' },
      { chinese: '面包', english: 'bread' },
      { chinese: '生日', english: 'birthday' },
      { chinese: '晚餐', english: 'dinner' },
      { chinese: '周', english: 'week' },
      { chinese: '食物', english: 'food' },
      { chinese: '当然', english: 'sure' },
      { chinese: '蔬菜', english: 'vegetable' },
      { chinese: '水果', english: 'fruit' },
      { chinese: '正确的', english: 'right' },
      { chinese: '苹果', english: 'apple' },
      { chinese: '鸡蛋', english: 'egg' },
      { chinese: '胡萝卜', english: 'carrot' },
      { chinese: '米饭', english: 'rice' },
      { chinese: '鸡肉', english: 'chicken' },
      { chinese: '那么', english: 'so' },
      { chinese: '早餐', english: 'breakfast' },
      { chinese: '午餐', english: 'lunch' },
      { chinese: '星星', english: 'star' },
      { chinese: '吃', english: 'eat' },
      { chinese: '健康的', english: 'healthy' },
      { chinese: '习惯', english: 'habit' },
      { chinese: '肥胖的', english: 'fat' },
    ]
  },
  {
    grade: '七年级', semester: '上册', unit: 'Unit 7',
    unitName: 'How much are these socks?',
    words: [
      { chinese: '许多', english: 'much' },
      { chinese: '短袜', english: 'sock' },
      { chinese: 'T恤衫', english: 'T-shirt' },
      { chinese: '短裤', english: 'shorts' },
      { chinese: '毛衣', english: 'sweater' },
      { chinese: '裤子', english: 'trousers' },
      { chinese: '鞋子', english: 'shoe' },
      { chinese: '裙子', english: 'skirt' },
      { chinese: '美元', english: 'dollar' },
      { chinese: '大的', english: 'big' },
      { chinese: '小的', english: 'small' },
      { chinese: '短的', english: 'short' },
      { chinese: '长的', english: 'long' },
      { chinese: '女人', english: 'woman' },
      { chinese: '需要', english: 'need' },
      { chinese: '看', english: 'look' },
      { chinese: '一双', english: 'pair' },
      { chinese: '买', english: 'buy' },
      { chinese: '出售', english: 'sell' },
      { chinese: '价格', english: 'price' },
      { chinese: '男孩', english: 'boy' },
      { chinese: '衣服', english: 'clothes' },
      { chinese: '商店', english: 'store' },
      { chinese: '所有的', english: 'all' },
      { chinese: '非常', english: 'very' },
      { chinese: '颜色', english: 'color' },
    ]
  },
]

// 人教版七年级下册词汇
const PEP_7B_UNITS: TextbookUnit[] = [
  {
    grade: '七年级', semester: '下册', unit: 'Unit 1',
    unitName: 'Can you play the guitar?',
    words: [
      { chinese: '吉他', english: 'guitar' },
      { chinese: '唱', english: 'sing' },
      { chinese: '游泳', english: 'swim' },
      { chinese: '跳舞', english: 'dance' },
      { chinese: '画画', english: 'draw' },
      { chinese: '国际象棋', english: 'chess' },
      { chinese: '参加', english: 'join' },
      { chinese: '俱乐部', english: 'club' },
      { chinese: '讲述', english: 'tell' },
      { chinese: '故事', english: 'story' },
      { chinese: '写作', english: 'write' },
      { chinese: '演出', english: 'show' },
      { chinese: '或者', english: 'or' },
      { chinese: '谈话', english: 'talk' },
      { chinese: '鼓', english: 'drum' },
      { chinese: '钢琴', english: 'piano' },
      { chinese: '小提琴', english: 'violin' },
      { chinese: '也', english: 'also' },
      { chinese: '人们', english: 'people' },
      { chinese: '家', english: 'home' },
      { chinese: '今天', english: 'today' },
      { chinese: '中心', english: 'center' },
      { chinese: '周末', english: 'weekend' },
      { chinese: '教', english: 'teach' },
      { chinese: '音乐家', english: 'musician' },
    ]
  },
  {
    grade: '七年级', semester: '下册', unit: 'Unit 2',
    unitName: 'What time do you go to school?',
    words: [
      { chinese: '向上', english: 'up' },
      { chinese: '穿衣服', english: 'dress' },
      { chinese: '刷', english: 'brush' },
      { chinese: '牙齿', english: 'tooth' },
      { chinese: '淋浴', english: 'shower' },
      { chinese: '通常', english: 'usually' },
      { chinese: '四十', english: 'forty' },
      { chinese: '从不', english: 'never' },
      { chinese: '早的', english: 'early' },
      { chinese: '五十', english: 'fifty' },
      { chinese: '工作', english: 'job' },
      { chinese: '工作', english: 'work' },
      { chinese: '车站', english: 'station' },
      { chinese: '广播电台', english: 'radio' },
      { chinese: '晚上', english: 'night' },
      { chinese: '滑稽的', english: 'funny' },
      { chinese: '锻炼', english: 'exercise' },
      { chinese: '最好的', english: 'best' },
      { chinese: '组', english: 'group' },
      { chinese: '一半', english: 'half' },
      { chinese: '过去', english: 'past' },
      { chinese: '一刻钟', english: 'quarter' },
      { chinese: '家庭作业', english: 'homework' },
      { chinese: '跑', english: 'run' },
      { chinese: '打扫', english: 'clean' },
      { chinese: '行走', english: 'walk' },
      { chinese: '快的', english: 'quickly' },
      { chinese: '或者', english: 'either' },
      { chinese: '大量', english: 'lot' },
      { chinese: '有时候', english: 'sometimes' },
      { chinese: '品尝', english: 'taste' },
      { chinese: '生活', english: 'life' },
    ]
  },
  {
    grade: '七年级', semester: '下册', unit: 'Unit 3',
    unitName: 'How do you get to school?',
    words: [
      { chinese: '火车', english: 'train' },
      { chinese: '公共汽车', english: 'bus' },
      { chinese: '地铁', english: 'subway' },
      { chinese: '骑', english: 'ride' },
      { chinese: '自行车', english: 'bike' },
      { chinese: '六十', english: 'sixty' },
      { chinese: '七十', english: 'seventy' },
      { chinese: '八十', english: 'eighty' },
      { chinese: '九十', english: 'ninety' },
      { chinese: '一百', english: 'hundred' },
      { chinese: '分钟', english: 'minute' },
      { chinese: '远的', english: 'far' },
      { chinese: '公里', english: 'kilometer' },
      { chinese: '新的', english: 'new' },
      { chinese: '每一个', english: 'every' },
      { chinese: '乘（交通工具）', english: 'by' },
      { chinese: '开车', english: 'drive' },
      { chinese: '居住', english: 'live' },
      { chinese: '车站', english: 'stop' },
      { chinese: '横过', english: 'cross' },
      { chinese: '河', english: 'river' },
      { chinese: '许多', english: 'many' },
      { chinese: '村庄', english: 'village' },
      { chinese: '在…之间', english: 'between' },
      { chinese: '桥', english: 'bridge' },
      { chinese: '小船', english: 'boat' },
      { chinese: '年', english: 'year' },
      { chinese: '害怕', english: 'afraid' },
      { chinese: '像', english: 'like' },
      { chinese: '村民', english: 'villager' },
      { chinese: '离开', english: 'leave' },
      { chinese: '梦想', english: 'dream' },
      { chinese: '真的', english: 'true' },
    ]
  },
  {
    grade: '七年级', semester: '下册', unit: 'Unit 4',
    unitName: 'Don\'t eat in class.',
    words: [
      { chinese: '规则', english: 'rule' },
      { chinese: '到达', english: 'arrive' },
      { chinese: '大厅', english: 'hall' },
      { chinese: '听', english: 'listen' },
      { chinese: '打架', english: 'fight' },
      { chinese: '抱歉', english: 'sorry' },
      { chinese: '外面的', english: 'outside' },
      { chinese: '穿', english: 'wear' },
      { chinese: '重要的', english: 'important' },
      { chinese: '带来', english: 'bring' },
      { chinese: '安静的', english: 'quiet' },
      { chinese: '外出', english: 'out' },
      { chinese: '练习', english: 'practice' },
      { chinese: '碟', english: 'dish' },
      { chinese: '在…以前', english: 'before' },
      { chinese: '脏的', english: 'dirty' },
      { chinese: '厨房', english: 'kitchen' },
      { chinese: '更多的', english: 'more' },
      { chinese: '吵闹的', english: 'noisy' },
      { chinese: '放松', english: 'relax' },
      { chinese: '阅读', english: 'read' },
      { chinese: '可怕的', english: 'terrible' },
      { chinese: '感觉', english: 'feel' },
      { chinese: '严格的', english: 'strict' },
      { chinese: '记住', english: 'remember' },
      { chinese: '跟随', english: 'follow' },
      { chinese: '运气', english: 'luck' },
      { chinese: '保持', english: 'keep' },
      { chinese: '头发', english: 'hair' },
      { chinese: '学习', english: 'learn' },
    ]
  },
  {
    grade: '七年级', semester: '下册', unit: 'Unit 5',
    unitName: 'Why do you like pandas?',
    words: [
      { chinese: '熊猫', english: 'panda' },
      { chinese: '动物园', english: 'zoo' },
      { chinese: '老虎', english: 'tiger' },
      { chinese: '大象', english: 'elephant' },
      { chinese: '考拉', english: 'koala' },
      { chinese: '狮子', english: 'lion' },
      { chinese: '长颈鹿', english: 'giraffe' },
      { chinese: '动物', english: 'animal' },
      { chinese: '可爱的', english: 'cute' },
      { chinese: '懒惰的', english: 'lazy' },
      { chinese: '聪明的', english: 'smart' },
      { chinese: '美丽的', english: 'beautiful' },
      { chinese: '吓人的', english: 'scary' },
      { chinese: '种类', english: 'kind' },
      { chinese: '澳大利亚', english: 'Australia' },
      { chinese: '南方', english: 'south' },
      { chinese: '非洲', english: 'Africa' },
      { chinese: '宠物', english: 'pet' },
      { chinese: '腿', english: 'leg' },
      { chinese: '猫', english: 'cat' },
      { chinese: '睡觉', english: 'sleep' },
      { chinese: '友好的', english: 'friendly' },
      { chinese: '害羞的', english: 'shy' },
      { chinese: '拯救', english: 'save' },
      { chinese: '象征', english: 'symbol' },
      { chinese: '旗帜', english: 'flag' },
      { chinese: '忘记', english: 'forget' },
      { chinese: '地方', english: 'place' },
      { chinese: '水', english: 'water' },
      { chinese: '危险', english: 'danger' },
      { chinese: '砍', english: 'cut' },
      { chinese: '向下', english: 'down' },
      { chinese: '树', english: 'tree' },
      { chinese: '杀死', english: 'kill' },
      { chinese: '由…制成', english: 'made' },
    ]
  },
]

// 人教版八年级上册核心词汇
const PEP_8A_UNITS: TextbookUnit[] = [
  {
    grade: '八年级', semester: '上册', unit: 'Unit 1',
    unitName: 'Where did you go on vacation?',
    words: [
      { chinese: '任何人', english: 'anyone' },
      { chinese: '在任何地方', english: 'anywhere' },
      { chinese: '精彩的', english: 'wonderful' },
      { chinese: '不多', english: 'few' },
      { chinese: '最多', english: 'most' },
      { chinese: '某事', english: 'something' },
      { chinese: '没有什么', english: 'nothing' },
      { chinese: '每人', english: 'everyone' },
      { chinese: '我自己', english: 'myself' },
      { chinese: '你自己', english: 'yourself' },
      { chinese: '母鸡', english: 'hen' },
      { chinese: '猪', english: 'pig' },
      { chinese: '好像', english: 'seem' },
      { chinese: '厌倦的', english: 'bored' },
      { chinese: '某人', english: 'someone' },
      { chinese: '日记', english: 'diary' },
      { chinese: '活动', english: 'activity' },
      { chinese: '决定', english: 'decide' },
      { chinese: '尝试', english: 'try' },
      { chinese: '滑翔伞', english: 'paragliding' },
      { chinese: '鸟', english: 'bird' },
      { chinese: '自行车', english: 'bicycle' },
      { chinese: '建筑物', english: 'building' },
      { chinese: '商人', english: 'trader' },
      { chinese: '想知道', english: 'wonder' },
      { chinese: '差别', english: 'difference' },
      { chinese: '顶部', english: 'top' },
      { chinese: '等待', english: 'wait' },
      { chinese: '伞', english: 'umbrella' },
      { chinese: '湿的', english: 'wet' },
      { chinese: '因为', english: 'because' },
      { chinese: '在…下面', english: 'below' },
      { chinese: '足够的', english: 'enough' },
      { chinese: '饥饿的', english: 'hungry' },
      { chinese: '像', english: 'as' },
      { chinese: '小山', english: 'hill' },
    ]
  },
  {
    grade: '八年级', semester: '上册', unit: 'Unit 2',
    unitName: 'How often do you exercise?',
    words: [
      { chinese: '家务', english: 'housework' },
      { chinese: '几乎不', english: 'hardly' },
      { chinese: '曾经', english: 'ever' },
      { chinese: '一次', english: 'once' },
      { chinese: '两次', english: 'twice' },
      { chinese: '互联网', english: 'Internet' },
      { chinese: '节目', english: 'program' },
      { chinese: '满的', english: 'full' },
      { chinese: '摆动', english: 'swing' },
      { chinese: '大概', english: 'maybe' },
      { chinese: '最少的', english: 'least' },
      { chinese: '垃圾食品', english: 'junk' },
      { chinese: '咖啡', english: 'coffee' },
      { chinese: '健康', english: 'health' },
      { chinese: '结果', english: 'result' },
      { chinese: '百分之', english: 'percent' },
      { chinese: '在线的', english: 'online' },
      { chinese: '电视', english: 'television' },
      { chinese: '虽然', english: 'although' },
      { chinese: '通过', english: 'through' },
      { chinese: '头脑', english: 'mind' },
      { chinese: '身体', english: 'body' },
      { chinese: '这样的', english: 'such' },
      { chinese: '一起', english: 'together' },
      { chinese: '死亡', english: 'die' },
      { chinese: '作者', english: 'writer' },
      { chinese: '牙医', english: 'dentist' },
      { chinese: '杂志', english: 'magazine' },
      { chinese: '然而', english: 'however' },
      { chinese: '比', english: 'than' },
      { chinese: '几乎', english: 'almost' },
      { chinese: '没有一个', english: 'none' },
      { chinese: '较少', english: 'less' },
      { chinese: '分数', english: 'point' },
    ]
  },
  {
    grade: '八年级', semester: '上册', unit: 'Unit 3',
    unitName: 'I\'m more outgoing than my sister.',
    words: [
      { chinese: '外向的', english: 'outgoing' },
      { chinese: '更好的', english: 'better' },
      { chinese: '大声地', english: 'loudly' },
      { chinese: '安静地', english: 'quietly' },
      { chinese: '工作努力的', english: 'hard-working' },
      { chinese: '比赛', english: 'competition' },
      { chinese: '极好的', english: 'fantastic' },
      { chinese: '哪一个', english: 'which' },
      { chinese: '清楚地', english: 'clearly' },
      { chinese: '赢得', english: 'win' },
      { chinese: '不过', english: 'though' },
      { chinese: '有才能的', english: 'talented' },
      { chinese: '真正', english: 'truly' },
      { chinese: '关心', english: 'care' },
      { chinese: '严肃的', english: 'serious' },
      { chinese: '镜子', english: 'mirror' },
      { chinese: '小孩', english: 'kid' },
      { chinese: '必需的', english: 'necessary' },
      { chinese: '两个都', english: 'both' },
      { chinese: '成绩', english: 'grade' },
      { chinese: '应该', english: 'should' },
      { chinese: '谚语', english: 'saying' },
      { chinese: '伸手', english: 'reach' },
      { chinese: '手', english: 'hand' },
      { chinese: '心', english: 'heart' },
      { chinese: '事实', english: 'fact' },
      { chinese: '打破', english: 'break' },
      { chinese: '手臂', english: 'arm' },
      { chinese: '分享', english: 'share' },
      { chinese: '响亮的', english: 'loud' },
      { chinese: '相似的', english: 'similar' },
    ]
  },
  {
    grade: '八年级', semester: '上册', unit: 'Unit 4',
    unitName: 'What\'s the best movie theater?',
    words: [
      { chinese: '剧院', english: 'theater' },
      { chinese: '舒适的', english: 'comfortable' },
      { chinese: '座位', english: 'seat' },
      { chinese: '屏幕', english: 'screen' },
      { chinese: '接近', english: 'close' },
      { chinese: '票', english: 'ticket' },
      { chinese: '最差的', english: 'worst' },
      { chinese: '便宜地', english: 'cheaply' },
      { chinese: '歌', english: 'song' },
      { chinese: '选择', english: 'choose' },
      { chinese: '仔细地', english: 'carefully' },
      { chinese: '记者', english: 'reporter' },
      { chinese: '到目前为止', english: 'far' },
      { chinese: '新鲜的', english: 'fresh' },
      { chinese: '舒适地', english: 'comfortably' },
      { chinese: '更差的', english: 'worse' },
      { chinese: '服务', english: 'service' },
      { chinese: '相当', english: 'pretty' },
      { chinese: '菜单', english: 'menu' },
      { chinese: '表演', english: 'act' },
      { chinese: '每人', english: 'performer' },
      { chinese: '有创造力的', english: 'creative' },
      { chinese: '天赋', english: 'talent' },
      { chinese: '拥有', english: 'have' },
      { chinese: '贫穷的', english: 'poor' },
      { chinese: '拥挤的', english: 'crowded' },
    ]
  },
]

// ============================================================
// 人教版 PEP 小学英语 (三年级起点)
// ============================================================

const PEP_3A_UNITS: TextbookUnit[] = [
  { grade: '三年级', semester: '上册', unit: 'Unit 1', unitName: 'Hello!',
    words: [
      { chinese: '尺子', english: 'ruler' }, { chinese: '铅笔', english: 'pencil' },
      { chinese: '橡皮', english: 'eraser' }, { chinese: '蜡笔', english: 'crayon' },
      { chinese: '包', english: 'bag' }, { chinese: '钢笔', english: 'pen' },
      { chinese: '书', english: 'book' }, { chinese: '不', english: 'no' },
      { chinese: '你的', english: 'your' },
    ]
  },
  { grade: '三年级', semester: '上册', unit: 'Unit 2', unitName: 'Colours',
    words: [
      { chinese: '红色', english: 'red' }, { chinese: '绿色', english: 'green' },
      { chinese: '黄色', english: 'yellow' }, { chinese: '蓝色', english: 'blue' },
      { chinese: '黑色', english: 'black' }, { chinese: '棕色', english: 'brown' },
      { chinese: '白色', english: 'white' }, { chinese: '橙色', english: 'orange' },
      { chinese: '好的', english: 'okay' }, { chinese: '妈妈', english: 'mum' },
    ]
  },
  { grade: '三年级', semester: '上册', unit: 'Unit 3', unitName: 'Look at me!',
    words: [
      { chinese: '脸', english: 'face' }, { chinese: '耳朵', english: 'ear' },
      { chinese: '眼睛', english: 'eye' }, { chinese: '鼻子', english: 'nose' },
      { chinese: '嘴巴', english: 'mouth' }, { chinese: '手臂', english: 'arm' },
      { chinese: '手', english: 'hand' }, { chinese: '头', english: 'head' },
      { chinese: '身体', english: 'body' }, { chinese: '腿', english: 'leg' },
      { chinese: '脚', english: 'foot' }, { chinese: '学校', english: 'school' },
    ]
  },
  { grade: '三年级', semester: '上册', unit: 'Unit 4', unitName: 'We love animals',
    words: [
      { chinese: '鸭子', english: 'duck' }, { chinese: '猪', english: 'pig' },
      { chinese: '猫', english: 'cat' }, { chinese: '熊', english: 'bear' },
      { chinese: '狗', english: 'dog' }, { chinese: '大象', english: 'elephant' },
      { chinese: '猴子', english: 'monkey' }, { chinese: '鸟', english: 'bird' },
      { chinese: '老虎', english: 'tiger' }, { chinese: '熊猫', english: 'panda' },
      { chinese: '动物园', english: 'zoo' }, { chinese: '有趣的', english: 'funny' },
    ]
  },
  { grade: '三年级', semester: '上册', unit: 'Unit 5', unitName: 'Let\'s eat!',
    words: [
      { chinese: '面包', english: 'bread' }, { chinese: '果汁', english: 'juice' },
      { chinese: '鸡蛋', english: 'egg' }, { chinese: '牛奶', english: 'milk' },
      { chinese: '水', english: 'water' }, { chinese: '蛋糕', english: 'cake' },
      { chinese: '鱼', english: 'fish' }, { chinese: '米饭', english: 'rice' },
    ]
  },
  { grade: '三年级', semester: '上册', unit: 'Unit 6', unitName: 'Happy birthday!',
    words: [
      { chinese: '一', english: 'one' }, { chinese: '二', english: 'two' },
      { chinese: '三', english: 'three' }, { chinese: '四', english: 'four' },
      { chinese: '五', english: 'five' }, { chinese: '六', english: 'six' },
      { chinese: '七', english: 'seven' }, { chinese: '八', english: 'eight' },
      { chinese: '九', english: 'nine' }, { chinese: '十', english: 'ten' },
      { chinese: '兄弟', english: 'brother' }, { chinese: '盘子', english: 'plate' },
    ]
  },
]

const PEP_3B_UNITS: TextbookUnit[] = [
  { grade: '三年级', semester: '下册', unit: 'Unit 1', unitName: 'Welcome back to school!',
    words: [
      { chinese: '英国', english: 'UK' }, { chinese: '加拿大', english: 'Canada' },
      { chinese: '美国', english: 'USA' }, { chinese: '中国', english: 'China' },
      { chinese: '她', english: 'she' }, { chinese: '他', english: 'he' },
      { chinese: '学生', english: 'student' }, { chinese: '老师', english: 'teacher' },
      { chinese: '男孩', english: 'boy' }, { chinese: '女孩', english: 'girl' },
      { chinese: '新的', english: 'new' }, { chinese: '朋友', english: 'friend' },
    ]
  },
  { grade: '三年级', semester: '下册', unit: 'Unit 2', unitName: 'My family',
    words: [
      { chinese: '父亲', english: 'father' }, { chinese: '爸爸', english: 'dad' },
      { chinese: '母亲', english: 'mother' }, { chinese: '妈妈', english: 'mum' },
      { chinese: '男人', english: 'man' }, { chinese: '女人', english: 'woman' },
      { chinese: '祖父', english: 'grandfather' }, { chinese: '祖母', english: 'grandmother' },
      { chinese: '姐妹', english: 'sister' }, { chinese: '兄弟', english: 'brother' },
      { chinese: '家庭', english: 'family' },
    ]
  },
  { grade: '三年级', semester: '下册', unit: 'Unit 3', unitName: 'At the zoo',
    words: [
      { chinese: '胖的', english: 'fat' }, { chinese: '瘦的', english: 'thin' },
      { chinese: '高的', english: 'tall' }, { chinese: '矮的', english: 'short' },
      { chinese: '小的', english: 'small' }, { chinese: '大的', english: 'big' },
      { chinese: '长的', english: 'long' }, { chinese: '尾巴', english: 'tail' },
      { chinese: '长颈鹿', english: 'giraffe' },
    ]
  },
  { grade: '三年级', semester: '下册', unit: 'Unit 4', unitName: 'Where is my car?',
    words: [
      { chinese: '在…上面', english: 'on' }, { chinese: '在…里面', english: 'in' },
      { chinese: '在…下面', english: 'under' }, { chinese: '椅子', english: 'chair' },
      { chinese: '桌子', english: 'desk' }, { chinese: '帽子', english: 'cap' },
      { chinese: '球', english: 'ball' }, { chinese: '小汽车', english: 'car' },
      { chinese: '船', english: 'boat' }, { chinese: '地图', english: 'map' },
    ]
  },
  { grade: '三年级', semester: '下册', unit: 'Unit 5', unitName: 'Do you like pears?',
    words: [
      { chinese: '梨', english: 'pear' }, { chinese: '苹果', english: 'apple' },
      { chinese: '橙子', english: 'orange' }, { chinese: '香蕉', english: 'banana' },
      { chinese: '西瓜', english: 'watermelon' }, { chinese: '草莓', english: 'strawberry' },
      { chinese: '葡萄', english: 'grape' }, { chinese: '水果', english: 'fruit' },
      { chinese: '买', english: 'buy' },
    ]
  },
  { grade: '三年级', semester: '下册', unit: 'Unit 6', unitName: 'How many?',
    words: [
      { chinese: '十一', english: 'eleven' }, { chinese: '十二', english: 'twelve' },
      { chinese: '十三', english: 'thirteen' }, { chinese: '十四', english: 'fourteen' },
      { chinese: '十五', english: 'fifteen' }, { chinese: '十六', english: 'sixteen' },
      { chinese: '十七', english: 'seventeen' }, { chinese: '十八', english: 'eighteen' },
      { chinese: '十九', english: 'nineteen' }, { chinese: '二十', english: 'twenty' },
      { chinese: '风筝', english: 'kite' }, { chinese: '美丽的', english: 'beautiful' },
    ]
  },
]

const PEP_4A_UNITS: TextbookUnit[] = [
  { grade: '四年级', semester: '上册', unit: 'Unit 1', unitName: 'My classroom',
    words: [
      { chinese: '教室', english: 'classroom' }, { chinese: '窗户', english: 'window' },
      { chinese: '门', english: 'door' }, { chinese: '图画', english: 'picture' },
      { chinese: '黑板', english: 'blackboard' }, { chinese: '灯', english: 'light' },
      { chinese: '墙壁', english: 'wall' }, { chinese: '地板', english: 'floor' },
      { chinese: '电脑', english: 'computer' }, { chinese: '讲台', english: 'desk' },
      { chinese: '帮助', english: 'help' }, { chinese: '打扫', english: 'clean' },
    ]
  },
  { grade: '四年级', semester: '上册', unit: 'Unit 2', unitName: 'My schoolbag',
    words: [
      { chinese: '书包', english: 'schoolbag' }, { chinese: '数学书', english: 'maths' },
      { chinese: '英语书', english: 'English' }, { chinese: '语文书', english: 'Chinese' },
      { chinese: '故事书', english: 'storybook' }, { chinese: '糖果', english: 'candy' },
      { chinese: '笔记本', english: 'notebook' }, { chinese: '玩具', english: 'toy' },
      { chinese: '钥匙', english: 'key' }, { chinese: '丢失', english: 'lost' },
    ]
  },
  { grade: '四年级', semester: '上册', unit: 'Unit 3', unitName: 'My friends',
    words: [
      { chinese: '强壮的', english: 'strong' }, { chinese: '友好的', english: 'friendly' },
      { chinese: '安静的', english: 'quiet' }, { chinese: '头发', english: 'hair' },
      { chinese: '鞋子', english: 'shoe' }, { chinese: '眼镜', english: 'glasses' },
      { chinese: '帽子', english: 'hat' }, { chinese: '他的', english: 'his' },
      { chinese: '她的', english: 'her' }, { chinese: '正确的', english: 'right' },
    ]
  },
  { grade: '四年级', semester: '上册', unit: 'Unit 4', unitName: 'My home',
    words: [
      { chinese: '卧室', english: 'bedroom' }, { chinese: '客厅', english: 'living' },
      { chinese: '书房', english: 'study' }, { chinese: '厨房', english: 'kitchen' },
      { chinese: '浴室', english: 'bathroom' }, { chinese: '床', english: 'bed' },
      { chinese: '电话', english: 'phone' }, { chinese: '桌子', english: 'table' },
      { chinese: '沙发', english: 'sofa' }, { chinese: '冰箱', english: 'fridge' },
      { chinese: '找到', english: 'find' },
    ]
  },
  { grade: '四年级', semester: '上册', unit: 'Unit 5', unitName: 'Dinner\'s ready',
    words: [
      { chinese: '牛肉', english: 'beef' }, { chinese: '鸡肉', english: 'chicken' },
      { chinese: '面条', english: 'noodle' }, { chinese: '汤', english: 'soup' },
      { chinese: '蔬菜', english: 'vegetable' }, { chinese: '筷子', english: 'chopsticks' },
      { chinese: '碗', english: 'bowl' }, { chinese: '餐叉', english: 'fork' },
      { chinese: '刀', english: 'knife' }, { chinese: '勺子', english: 'spoon' },
      { chinese: '晚餐', english: 'dinner' }, { chinese: '尝试', english: 'try' },
    ]
  },
  { grade: '四年级', semester: '上册', unit: 'Unit 6', unitName: 'Meet my family!',
    words: [
      { chinese: '父母', english: 'parents' }, { chinese: '堂兄弟', english: 'cousin' },
      { chinese: '叔叔', english: 'uncle' }, { chinese: '阿姨', english: 'aunt' },
      { chinese: '婴儿', english: 'baby' }, { chinese: '医生', english: 'doctor' },
      { chinese: '厨师', english: 'cook' }, { chinese: '司机', english: 'driver' },
      { chinese: '农民', english: 'farmer' }, { chinese: '护士', english: 'nurse' },
      { chinese: '工作', english: 'job' }, { chinese: '篮球', english: 'basketball' },
    ]
  },
]

const PEP_4B_UNITS: TextbookUnit[] = [
  { grade: '四年级', semester: '下册', unit: 'Unit 1', unitName: 'My school',
    words: [
      { chinese: '一楼', english: 'first' }, { chinese: '二楼', english: 'second' },
      { chinese: '教师办公室', english: 'teachers\'' }, { chinese: '图书馆', english: 'library' },
      { chinese: '操场', english: 'playground' }, { chinese: '花园', english: 'garden' },
      { chinese: '作业', english: 'homework' }, { chinese: '四十', english: 'forty' },
      { chinese: '方向', english: 'way' },
    ]
  },
  { grade: '四年级', semester: '下册', unit: 'Unit 2', unitName: 'What time is it?',
    words: [
      { chinese: '早餐', english: 'breakfast' }, { chinese: '午餐', english: 'lunch' },
      { chinese: '英语课', english: 'English' }, { chinese: '音乐课', english: 'music' },
      { chinese: '体育课', english: 'PE' }, { chinese: '晚餐', english: 'dinner' },
      { chinese: '起床', english: 'get' }, { chinese: '去', english: 'go' },
      { chinese: '回家', english: 'home' }, { chinese: '钟', english: 'clock' },
      { chinese: '三十', english: 'thirty' },
    ]
  },
  { grade: '四年级', semester: '下册', unit: 'Unit 3', unitName: 'Weather',
    words: [
      { chinese: '寒冷的', english: 'cold' }, { chinese: '凉爽的', english: 'cool' },
      { chinese: '温暖的', english: 'warm' }, { chinese: '炎热的', english: 'hot' },
      { chinese: '晴朗的', english: 'sunny' }, { chinese: '多风的', english: 'windy' },
      { chinese: '多云的', english: 'cloudy' }, { chinese: '下雪的', english: 'snowy' },
      { chinese: '下雨的', english: 'rainy' }, { chinese: '天气', english: 'weather' },
      { chinese: '外面', english: 'outside' }, { chinese: '小心', english: 'careful' },
    ]
  },
  { grade: '四年级', semester: '下册', unit: 'Unit 4', unitName: 'At the farm',
    words: [
      { chinese: '西红柿', english: 'tomato' }, { chinese: '土豆', english: 'potato' },
      { chinese: '胡萝卜', english: 'carrot' }, { chinese: '豆角', english: 'bean' },
      { chinese: '马', english: 'horse' }, { chinese: '牛', english: 'cow' },
      { chinese: '绵羊', english: 'sheep' }, { chinese: '母鸡', english: 'hen' },
      { chinese: '动物', english: 'animal' }, { chinese: '花园', english: 'garden' },
      { chinese: '农场', english: 'farm' }, { chinese: '山羊', english: 'goat' },
    ]
  },
  { grade: '四年级', semester: '下册', unit: 'Unit 5', unitName: 'My clothes',
    words: [
      { chinese: '衣服', english: 'clothes' }, { chinese: '裤子', english: 'pants' },
      { chinese: '帽子', english: 'hat' }, { chinese: '连衣裙', english: 'dress' },
      { chinese: '裙子', english: 'skirt' }, { chinese: '外套', english: 'coat' },
      { chinese: '毛衣', english: 'sweater' }, { chinese: '短袜', english: 'sock' },
      { chinese: '衬衫', english: 'shirt' }, { chinese: '夹克', english: 'jacket' },
      { chinese: '谁的', english: 'whose' }, { chinese: '我的', english: 'mine' },
      { chinese: '打包', english: 'pack' },
    ]
  },
  { grade: '四年级', semester: '下册', unit: 'Unit 6', unitName: 'Shopping',
    words: [
      { chinese: '手套', english: 'gloves' }, { chinese: '围巾', english: 'scarf' },
      { chinese: '雨伞', english: 'umbrella' }, { chinese: '太阳镜', english: 'sunglasses' },
      { chinese: '漂亮的', english: 'pretty' }, { chinese: '昂贵的', english: 'expensive' },
      { chinese: '便宜的', english: 'cheap' }, { chinese: '好的', english: 'nice' },
      { chinese: '试穿', english: 'try' }, { chinese: '尺码', english: 'size' },
      { chinese: '当然', english: 'sure' }, { chinese: '美元', english: 'dollar' },
    ]
  },
]

const PEP_5A_UNITS: TextbookUnit[] = [
  { grade: '五年级', semester: '上册', unit: 'Unit 1', unitName: 'What\'s he like?',
    words: [
      { chinese: '年老的', english: 'old' }, { chinese: '年轻的', english: 'young' },
      { chinese: '有趣的', english: 'funny' }, { chinese: '和蔼的', english: 'kind' },
      { chinese: '严格的', english: 'strict' }, { chinese: '有礼貌的', english: 'polite' },
      { chinese: '工作努力的', english: 'hard-working' }, { chinese: '有帮助的', english: 'helpful' },
      { chinese: '害羞的', english: 'shy' }, { chinese: '聪明的', english: 'clever' },
      { chinese: '知道', english: 'know' }, { chinese: '有时候', english: 'sometimes' },
    ]
  },
  { grade: '五年级', semester: '上册', unit: 'Unit 2', unitName: 'My week',
    words: [
      { chinese: '星期一', english: 'Monday' }, { chinese: '星期二', english: 'Tuesday' },
      { chinese: '星期三', english: 'Wednesday' }, { chinese: '星期四', english: 'Thursday' },
      { chinese: '星期五', english: 'Friday' }, { chinese: '星期六', english: 'Saturday' },
      { chinese: '星期日', english: 'Sunday' }, { chinese: '周末', english: 'weekend' },
      { chinese: '洗', english: 'wash' }, { chinese: '看', english: 'watch' },
      { chinese: '阅读', english: 'read' }, { chinese: '玩耍', english: 'play' },
      { chinese: '做', english: 'do' }, { chinese: '经常', english: 'often' },
      { chinese: '体育运动', english: 'sport' },
    ]
  },
  { grade: '五年级', semester: '上册', unit: 'Unit 3', unitName: 'What would you like?',
    words: [
      { chinese: '三明治', english: 'sandwich' }, { chinese: '沙拉', english: 'salad' },
      { chinese: '汉堡包', english: 'hamburger' }, { chinese: '冰激凌', english: 'ice cream' },
      { chinese: '茶', english: 'tea' }, { chinese: '新鲜的', english: 'fresh' },
      { chinese: '健康的', english: 'healthy' }, { chinese: '美味的', english: 'delicious' },
      { chinese: '辣的', english: 'hot' }, { chinese: '甜的', english: 'sweet' },
      { chinese: '最喜欢的', english: 'favourite' }, { chinese: '食物', english: 'food' },
      { chinese: '喝', english: 'drink' },
    ]
  },
  { grade: '五年级', semester: '上册', unit: 'Unit 4', unitName: 'What can you do?',
    words: [
      { chinese: '唱歌', english: 'sing' }, { chinese: '跳舞', english: 'dance' },
      { chinese: '画漫画', english: 'cartoon' }, { chinese: '弹琵琶', english: 'pipa' },
      { chinese: '功夫', english: 'kung fu' }, { chinese: '游泳', english: 'swim' },
      { chinese: '篮球', english: 'basketball' }, { chinese: '乒乓球', english: 'ping-pong' },
      { chinese: '说英语', english: 'English' }, { chinese: '烹饪', english: 'cook' },
      { chinese: '聚会', english: 'party' }, { chinese: '发送', english: 'send' },
      { chinese: '想要', english: 'want' },
    ]
  },
  { grade: '五年级', semester: '上册', unit: 'Unit 5', unitName: 'There is a big bed',
    words: [
      { chinese: '钟', english: 'clock' }, { chinese: '植物', english: 'plant' },
      { chinese: '瓶子', english: 'bottle' }, { chinese: '水瓶', english: 'water' },
      { chinese: '自行车', english: 'bike' }, { chinese: '照片', english: 'photo' },
      { chinese: '在…前面', english: 'front' }, { chinese: '在…之间', english: 'between' },
      { chinese: '在…上面', english: 'above' }, { chinese: '在…旁边', english: 'beside' },
      { chinese: '在…后面', english: 'behind' }, { chinese: '到处', english: 'everywhere' },
      { chinese: '物品', english: 'thing' },
    ]
  },
  { grade: '五年级', semester: '上册', unit: 'Unit 6', unitName: 'In a nature park',
    words: [
      { chinese: '森林', english: 'forest' }, { chinese: '湖', english: 'lake' },
      { chinese: '河', english: 'river' }, { chinese: '山', english: 'mountain' },
      { chinese: '小山', english: 'hill' }, { chinese: '桥', english: 'bridge' },
      { chinese: '村庄', english: 'village' }, { chinese: '房屋', english: 'house' },
      { chinese: '树', english: 'tree' }, { chinese: '建筑物', english: 'building' },
      { chinese: '高的', english: 'high' }, { chinese: '兔子', english: 'rabbit' },
    ]
  },
]

const PEP_5B_UNITS: TextbookUnit[] = [
  { grade: '五年级', semester: '下册', unit: 'Unit 1', unitName: 'My day',
    words: [
      { chinese: '吃早餐', english: 'breakfast' }, { chinese: '做早操', english: 'exercise' },
      { chinese: '上课', english: 'class' }, { chinese: '做运动', english: 'sports' },
      { chinese: '吃晚餐', english: 'dinner' }, { chinese: '散步', english: 'walk' },
      { chinese: '购物', english: 'shopping' }, { chinese: '打扫', english: 'clean' },
      { chinese: '总是', english: 'always' }, { chinese: '通常', english: 'usually' },
      { chinese: '有时候', english: 'sometimes' }, { chinese: '从不', english: 'never' },
    ]
  },
  { grade: '五年级', semester: '下册', unit: 'Unit 2', unitName: 'My favourite season',
    words: [
      { chinese: '春天', english: 'spring' }, { chinese: '夏天', english: 'summer' },
      { chinese: '秋天', english: 'autumn' }, { chinese: '冬天', english: 'winter' },
      { chinese: '季节', english: 'season' }, { chinese: '野餐', english: 'picnic' },
      { chinese: '摘苹果', english: 'pick' }, { chinese: '堆雪人', english: 'snowman' },
      { chinese: '游泳', english: 'swim' }, { chinese: '叶子', english: 'leaf' },
      { chinese: '颜色', english: 'colour' }, { chinese: '因为', english: 'because' },
    ]
  },
  { grade: '五年级', semester: '下册', unit: 'Unit 3', unitName: 'My school calendar',
    words: [
      { chinese: '一月', english: 'January' }, { chinese: '二月', english: 'February' },
      { chinese: '三月', english: 'March' }, { chinese: '四月', english: 'April' },
      { chinese: '五月', english: 'May' }, { chinese: '六月', english: 'June' },
      { chinese: '七月', english: 'July' }, { chinese: '八月', english: 'August' },
      { chinese: '九月', english: 'September' }, { chinese: '十月', english: 'October' },
      { chinese: '十一月', english: 'November' }, { chinese: '十二月', english: 'December' },
    ]
  },
  { grade: '五年级', semester: '下册', unit: 'Unit 4', unitName: 'When is the art show?',
    words: [
      { chinese: '第一', english: 'first' }, { chinese: '第二', english: 'second' },
      { chinese: '第三', english: 'third' }, { chinese: '第四', english: 'fourth' },
      { chinese: '第五', english: 'fifth' }, { chinese: '第十二', english: 'twelfth' },
      { chinese: '第二十', english: 'twentieth' }, { chinese: '特别的', english: 'special' },
      { chinese: '日记', english: 'diary' }, { chinese: '仍然', english: 'still' },
      { chinese: '吵闹的', english: 'noisy' }, { chinese: '睁开', english: 'open' },
    ]
  },
  { grade: '五年级', semester: '下册', unit: 'Unit 5', unitName: 'Whose dog is it?',
    words: [
      { chinese: '我的', english: 'mine' }, { chinese: '你的', english: 'yours' },
      { chinese: '他的', english: 'his' }, { chinese: '她的', english: 'hers' },
      { chinese: '他们的', english: 'theirs' }, { chinese: '我们的', english: 'ours' },
      { chinese: '喝', english: 'drink' }, { chinese: '睡觉', english: 'sleep' },
      { chinese: '跳', english: 'jump' }, { chinese: '爬', english: 'climb' },
      { chinese: '吃', english: 'eat' }, { chinese: '玩耍', english: 'play' },
      { chinese: '兴奋的', english: 'excited' },
    ]
  },
  { grade: '五年级', semester: '下册', unit: 'Unit 6', unitName: 'Work quietly!',
    words: [
      { chinese: '做早操', english: 'doing' }, { chinese: '上课', english: 'having' },
      { chinese: '读书', english: 'reading' }, { chinese: '听音乐', english: 'listening' },
      { chinese: '吃午饭', english: 'eating' }, { chinese: '保持', english: 'keep' },
      { chinese: '向右转', english: 'right' }, { chinese: '向左转', english: 'left' },
      { chinese: '展览', english: 'show' }, { chinese: '任何事物', english: 'anything' },
      { chinese: '竹子', english: 'bamboo' }, { chinese: '教', english: 'teach' },
    ]
  },
]

const PEP_6A_UNITS: TextbookUnit[] = [
  { grade: '六年级', semester: '上册', unit: 'Unit 1', unitName: 'How can I get there?',
    words: [
      { chinese: '科学', english: 'science' }, { chinese: '博物馆', english: 'museum' },
      { chinese: '邮局', english: 'post' }, { chinese: '书店', english: 'bookstore' },
      { chinese: '电影院', english: 'cinema' }, { chinese: '医院', english: 'hospital' },
      { chinese: '十字路口', english: 'crossing' }, { chinese: '转弯', english: 'turn' },
      { chinese: '左边', english: 'left' }, { chinese: '右边', english: 'right' },
      { chinese: '直的', english: 'straight' }, { chinese: '问路', english: 'ask' },
      { chinese: '有趣的', english: 'interesting' }, { chinese: '到达', english: 'get' },
    ]
  },
  { grade: '六年级', semester: '上册', unit: 'Unit 2', unitName: 'Ways to go to school',
    words: [
      { chinese: '步行', english: 'foot' }, { chinese: '乘飞机', english: 'plane' },
      { chinese: '乘公共汽车', english: 'bus' }, { chinese: '乘火车', english: 'train' },
      { chinese: '乘出租车', english: 'taxi' }, { chinese: '乘轮船', english: 'ship' },
      { chinese: '地铁', english: 'subway' }, { chinese: '慢的', english: 'slow' },
      { chinese: '快的', english: 'fast' }, { chinese: '头盔', english: 'helmet' },
      { chinese: '注意', english: 'attention' }, { chinese: '交通', english: 'traffic' },
      { chinese: '必须', english: 'must' }, { chinese: '穿', english: 'wear' },
    ]
  },
  { grade: '六年级', semester: '上册', unit: 'Unit 3', unitName: 'My weekend plan',
    words: [
      { chinese: '拜访', english: 'visit' }, { chinese: '电影', english: 'film' },
      { chinese: '旅行', english: 'trip' }, { chinese: '超市', english: 'supermarket' },
      { chinese: '晚上', english: 'evening' }, { chinese: '明天', english: 'tomorrow' },
      { chinese: '今晚', english: 'tonight' }, { chinese: '下周', english: 'next' },
      { chinese: '词典', english: 'dictionary' }, { chinese: '漫画书', english: 'comic' },
      { chinese: '单词书', english: 'word' }, { chinese: '明信片', english: 'postcard' },
      { chinese: '价格', english: 'price' },
    ]
  },
  { grade: '六年级', semester: '上册', unit: 'Unit 4', unitName: 'I have a pen pal',
    words: [
      { chinese: '学习', english: 'studies' }, { chinese: '远足', english: 'hiking' },
      { chinese: '谜语', english: 'puzzle' }, { chinese: '爱好', english: 'hobby' },
      { chinese: '想法', english: 'idea' }, { chinese: '令人惊奇的', english: 'amazing' },
      { chinese: '分享', english: 'share' }, { chinese: '加入', english: 'join' },
      { chinese: '俱乐部', english: 'club' }, { chinese: '目标', english: 'goal' },
    ]
  },
  { grade: '六年级', semester: '上册', unit: 'Unit 5', unitName: 'What does he do?',
    words: [
      { chinese: '工厂', english: 'factory' }, { chinese: '工人', english: 'worker' },
      { chinese: '邮递员', english: 'postman' }, { chinese: '商人', english: 'businessman' },
      { chinese: '警察', english: 'police' }, { chinese: '渔民', english: 'fisherman' },
      { chinese: '科学家', english: 'scientist' }, { chinese: '飞行员', english: 'pilot' },
      { chinese: '教练', english: 'coach' }, { chinese: '国家', english: 'country' },
      { chinese: '海洋', english: 'sea' }, { chinese: '保持', english: 'stay' },
    ]
  },
  { grade: '六年级', semester: '上册', unit: 'Unit 6', unitName: 'How do you feel?',
    words: [
      { chinese: '生气的', english: 'angry' }, { chinese: '害怕的', english: 'afraid' },
      { chinese: '伤心的', english: 'sad' }, { chinese: '担心的', english: 'worried' },
      { chinese: '高兴的', english: 'happy' }, { chinese: '穿', english: 'wear' },
      { chinese: '更多的', english: 'more' }, { chinese: '深的', english: 'deep' },
      { chinese: '呼吸', english: 'breath' }, { chinese: '数数', english: 'count' },
      { chinese: '追赶', english: 'chase' }, { chinese: '生病的', english: 'ill' },
      { chinese: '检查', english: 'check' },
    ]
  },
]

const PEP_6B_UNITS: TextbookUnit[] = [
  { grade: '六年级', semester: '下册', unit: 'Unit 1', unitName: 'How tall are you?',
    words: [
      { chinese: '更年轻的', english: 'younger' }, { chinese: '更年老的', english: 'older' },
      { chinese: '更高的', english: 'taller' }, { chinese: '更矮的', english: 'shorter' },
      { chinese: '更长的', english: 'longer' }, { chinese: '更瘦的', english: 'thinner' },
      { chinese: '更重的', english: 'heavier' }, { chinese: '更大的', english: 'bigger' },
      { chinese: '更小的', english: 'smaller' }, { chinese: '更强壮的', english: 'stronger' },
      { chinese: '恐龙', english: 'dinosaur' }, { chinese: '千克', english: 'kilogram' },
      { chinese: '米', english: 'meter' },
    ]
  },
  { grade: '六年级', semester: '下册', unit: 'Unit 2', unitName: 'Last weekend',
    words: [
      { chinese: '打扫了', english: 'cleaned' }, { chinese: '停留了', english: 'stayed' },
      { chinese: '洗了', english: 'washed' }, { chinese: '看了', english: 'watched' },
      { chinese: '喝了', english: 'drank' }, { chinese: '读了', english: 'read' },
      { chinese: '看见了', english: 'saw' }, { chinese: '睡了', english: 'slept' },
      { chinese: '昨天', english: 'yesterday' }, { chinese: '之前', english: 'before' },
      { chinese: '杂志', english: 'magazine' }, { chinese: '更好的', english: 'better' },
      { chinese: '酒店', english: 'hotel' }, { chinese: '灯', english: 'lamp' },
    ]
  },
  { grade: '六年级', semester: '下册', unit: 'Unit 3', unitName: 'Where did you go?',
    words: [
      { chinese: '去了', english: 'went' }, { chinese: '野营', english: 'camp' },
      { chinese: '钓鱼', english: 'fishing' }, { chinese: '骑了', english: 'rode' },
      { chinese: '伤了', english: 'hurt' }, { chinese: '吃了', english: 'ate' },
      { chinese: '买了', english: 'bought' }, { chinese: '礼物', english: 'gift' },
      { chinese: '海滩', english: 'beach' }, { chinese: '照相了', english: 'took' },
      { chinese: '劳动节', english: 'Labour' },
    ]
  },
  { grade: '六年级', semester: '下册', unit: 'Unit 4', unitName: 'Then and now',
    words: [
      { chinese: '饭厅', english: 'dining' }, { chinese: '体育馆', english: 'gym' },
      { chinese: '草地', english: 'grass' }, { chinese: '几年前', english: 'ago' },
      { chinese: '自行车', english: 'cycling' }, { chinese: '滑冰', english: 'ice-skate' },
      { chinese: '羽毛球', english: 'badminton' }, { chinese: '星星', english: 'star' },
      { chinese: '容易的', english: 'easy' }, { chinese: '查阅', english: 'look' },
      { chinese: '互联网', english: 'Internet' }, { chinese: '不同的', english: 'different' },
      { chinese: '活跃的', english: 'active' }, { chinese: '感觉', english: 'feel' },
      { chinese: '梦见', english: 'dream' },
    ]
  },
]

// 汇总所有单元
const ALL_PEP_UNITS: TextbookUnit[] = [
  ...PEP_3A_UNITS, ...PEP_3B_UNITS,
  ...PEP_4A_UNITS, ...PEP_4B_UNITS,
  ...PEP_5A_UNITS, ...PEP_5B_UNITS,
  ...PEP_6A_UNITS, ...PEP_6B_UNITS,
  ...PEP_7A_UNITS, ...PEP_7B_UNITS,
  ...PEP_8A_UNITS,
]

export function getUnitsByVersion(version: string): TextbookUnit[] {
  if (version === 'pep') return ALL_PEP_UNITS
  return []
}

export function getUnitsByGrade(version: string, grade: string): TextbookUnit[] {
  return getUnitsByVersion(version).filter(u => u.grade === grade)
}
